//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementIoT.Silicon.Resource.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElementIoT.Silicon.Resource.Messages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string key is not present in the configuration..
        /// </summary>
        public static string DataProvider_ConnectionStringKeyMissing {
            get {
                return ResourceManager.GetString("DataProvider_ConnectionStringKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data provider failed to save the given entity into the data base.
        /// </summary>
        public static string DataProvider_FailedtoSaveEntity {
            get {
                return ResourceManager.GetString("DataProvider_FailedtoSaveEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary key was not returned by the procedure.
        /// </summary>
        public static string DataProvider_PrimaryKeyWasNotReturned {
            get {
                return ResourceManager.GetString("DataProvider_PrimaryKeyWasNotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provisioing of the device failed while trying to add it to the IoT Hub.
        /// </summary>
        public static string IoTHubProvider_ProvisionDeviceIdentityFailed {
            get {
                return ResourceManager.GetString("IoTHubProvider_ProvisionDeviceIdentityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error while trying to save the device in the cache.
        /// </summary>
        public static string ProvisionDevice_CacheProviderUnexpected {
            get {
                return ResourceManager.GetString("ProvisionDevice_CacheProviderUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A device with the given Device ID has already been privisioned..
        /// </summary>
        public static string ProvisionDevice_DeviceExists {
            get {
                return ResourceManager.GetString("ProvisionDevice_DeviceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error while trying to provision the device in the IoT Hub.
        /// </summary>
        public static string ProvisionDevice_IoTProviderUnexpected {
            get {
                return ResourceManager.GetString("ProvisionDevice_IoTProviderUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error while trying to provision the device in the Platform Database.
        /// </summary>
        public static string ProvisionDevice_SqlProviderUnexpected {
            get {
                return ResourceManager.GetString("ProvisionDevice_SqlProviderUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is missing..
        /// </summary>
        public static string Service_CommandMissing {
            get {
                return ResourceManager.GetString("Service_CommandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service validation failed..
        /// </summary>
        public static string Service_ValidationFailed {
            get {
                return ResourceManager.GetString("Service_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Device entity is missing.
        /// </summary>
        public static string Validation_DeviceEntityMissing {
            get {
                return ResourceManager.GetString("Validation_DeviceEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Device identity is missing.
        /// </summary>
        public static string Validation_DeviceIdentityMissing {
            get {
                return ResourceManager.GetString("Validation_DeviceIdentityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device identifier use by the client is missing.
        /// </summary>
        public static string Validation_DeviceIDMissing {
            get {
                return ResourceManager.GetString("Validation_DeviceIDMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device type row key identifier is missing.
        /// </summary>
        public static string Validation_DeviceTypeKeyMissing {
            get {
                return ResourceManager.GetString("Validation_DeviceTypeKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IoT Hub device identifier is missing.
        /// </summary>
        public static string Validation_HubIDMissing {
            get {
                return ResourceManager.GetString("Validation_HubIDMissing", resourceCulture);
            }
        }
    }
}
